- hosts: bam-vm

  tasks:

    ### Prepare packages
    - name: "Update the apt cache if older than one day"
      sudo: yes
      apt: update_cache=yes cache_valid_time=86400

    ### Install prerequisites
    - name: "Ensure that necessary packages are installed"
      apt: name={{ item }} state=present
      sudo: yes
      with_items:
        - git
        - python-flask
        - python-dateutil
        - python-mechanize
        - python-requests
        - python-prettytable
        - python-setuptools
        - python-pandas

    ### Install cousteau
    - name: "Clone cousteau git repository"
      git: repo=https://github.com/RIPE-NCC/ripe-atlas-cousteau.git dest=/home/vagrant/ripe-atlas-cousteau

    ### Install flask-cache
    - name: "Clone flask-cache git repository"
      git: repo=https://github.com/thadeusb/flask-cache.git dest=/home/vagrant/flask-cache

    ### Set the PYTHONPATH variable
    - name: "Set the PYTHONPATH variable"
      lineinfile: dest=/home/vagrant/.profile line="export PYTHONPATH=/home/vagrant/ripe-atlas-cousteau/:/home/vagant/flask-cache/" create=yes

    ### Set the PYTHONPATH variable
    - name: "Set the PYTHONPATH variable"
      lineinfile: dest=/home/vagrant/.profile line="export PYTHONPATH=/home/vagrant/ripe-atlas-cousteau/:/home/vagrant/flask-cache/" create=yes

    ### Move to /vagrant on login
    - name: "Move to /vagrant on login"
      lineinfile: dest=/home/vagrant/.profile line="cd /vagrant/" create=yes
